# Configuration for clinic API deployment
app = "clinic-api-codg9g"
primary_region = "lhr"  # London region
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]
  [build.args]
    BP_GO_BUILD_COMMAND = "make build"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]
  
  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true
  
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  
  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    path = "/api/health"  # This endpoint will need to be implemented

[deploy]
  release_command = "go run cmd/migrate/main.go up"

[processes]
  app = "./bin/clinic"
